### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by ShaneBeee** [OfficialDonut/SkVault#1]
Hey Donut.... thanks a BUNCH for making this, I really appreciate it. 

I have 2 small requests. In the config section there are 2 things I was hoping you could possible make effects for. Let me see If i can explain this properly.

Lets say I make a skript that handles an economy. When a person downloads the skript i'd have to tell them to set these two variables in SkVault's config

```
currency_format: $%number%  <---- the format they would want
enable_automatic_linking: false <---- tell them to put this as false
```

I was wondering if you could make effects where this could be handled WITHIN a skript, so for example, someone would install this add-on and my skript, run them and the skript would automatically set those 2 items as they need to be.
**Example:**

```
on skript load:
    set skvault automatic linking to false
    set skvault currency format to "$%number%"
```

If this cant be done thats totally cool, I will work with what I got.

Thanks again for making this.

**Comment by OfficialDonut** [comment]
Definite yes for automatic linking (tbh ill probably remove it from the config and have all the stuff for automatic linking defined with effects because thats something the economy script should be handling, not the server owner). 

For the format (and currency names) I wouldve made a request event for them but as i said in the config, skript uses them while parsing your script. Im not sure if skript "re-gets" these values ever so retroactively changing them with an effect might not affect skript (it would be fine for other plugins getting the values). Ill have to look more into it. Possibly ill add the events and then give skript the config values the first time idk ill figure something out.

**Comment by ShaneBeee** [comment]
Ok awesome thanks :)
